# Generated by Codex on 2026-02-16

import decimal
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0002_alter_accountregistration_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                (
                    "vin",
                    models.CharField(
                        db_index=True,
                        max_length=17,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="VIN must be exactly 17 characters (letters and numbers, excluding I, O, and Q).",
                                regex="^[A-HJ-NPR-Z0-9]{17}$",
                            )
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("brake-parts", "Brake Parts"),
                            ("filters", "Filters"),
                            ("suspension", "Suspension"),
                            ("engine", "Engine Parts"),
                            ("electrical", "Electrical"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(decimal.Decimal("0.01"))],
                    ),
                ),
                ("initial_stock", models.PositiveIntegerField()),
                ("current_stock", models.PositiveIntegerField(blank=True, null=True)),
                ("reorder_level", models.PositiveIntegerField(default=0)),
                ("description", models.TextField()),
                ("product_image", models.ImageField(upload_to="product_images/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="products", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["vendor", "category"], name="App_product_vendor__20e00f_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["vendor", "is_active"], name="App_product_vendor__021f2f_idx"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(fields=("vendor", "name"), name="unique_vendor_product_name"),
        ),
    ]
