# Generated by Django 6.0.2 on 2026-02-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_product'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='App_product_vendor__a5d57b_idx',
            old_name='App_product_vendor__20e00f_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='App_product_vendor__780ca0_idx',
            old_name='App_product_vendor__021f2f_idx',
        ),
    ]
