# Generated by Codex on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0004_rename_app_product_vendor__20e00f_idx_app_product_vendor__a5d57b_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountregistration",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pictures/"),
        ),
    ]
