# Generated by Django 6.0.2 on 2026-03-06 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_siteannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vin',
            field=models.CharField(db_index=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Part Number must be 1 to 17 characters (letters and numbers, excluding I, O, and Q).', regex='^[A-HJ-NPR-Z0-9]{1,17}$')]),
        ),
    ]
